In [4]:
# import necessary torch libraries for tensors
import torch
import torch.nn as nn

Create a random tensor

In [5]:
# create a random 1-dimensional tensor 
x = torch.rand(5)
print(x)

tensor([0.7573, 0.3313, 0.9712, 0.0355, 0.6363])


Create an empty tensor

In [12]:
x = torch.empty(1)
print(x)
print('')


x = torch.ones(2,3)
print(x)
print('')

x = torch.zeros(2,3,3)
print(x)

tensor([5.4646e-05])

tensor([[1., 1., 1.],
        [1., 1., 1.]])

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])


Change dtype of a tensor

In [13]:
print(x.dtype)

torch.float32


In [14]:
x = torch.tensor([1,2,3], dtype=int)
print(x.dtype)

torch.int64


### Basic operations

In [15]:
x = torch.rand(2,2)
y = torch.rand(2,2)

print(x)
print(y)

tensor([[0.3452, 0.2851],
        [0.6058, 0.0415]])
tensor([[0.4390, 0.6712],
        [0.1573, 0.4442]])


Element-wise addition

In [16]:
z = x + y
print(z)

tensor([[0.7843, 0.9563],
        [0.7631, 0.4858]])


In [17]:
z = torch.add(x,y)
print(z)

tensor([[0.7843, 0.9563],
        [0.7631, 0.4858]])


In-place addition

In [18]:
# add all elements of x to y 
y.add_(x)
print(y)

tensor([[0.7843, 0.9563],
        [0.7631, 0.4858]])


*Funcitons with underscore at the end are in-place operations* 

Subtraction

In [19]:
z = x - y 
print(z)

z = torch.sub(x,y)
print(z)


tensor([[-0.4390, -0.6712],
        [-0.1573, -0.4442]])
tensor([[-0.4390, -0.6712],
        [-0.1573, -0.4442]])


Multiplication

In [20]:
z = x * y
print(z)

z = torch.mul(x,y)
print(z)

tensor([[0.2708, 0.2727],
        [0.4623, 0.0202]])
tensor([[0.2708, 0.2727],
        [0.4623, 0.0202]])


In-place multiplication

In [21]:
y.mul_(x)
print(y)

tensor([[0.2708, 0.2727],
        [0.4623, 0.0202]])


Division

In [22]:
z = x / y
print(z)

z = torch.div(x,y)
print(z)

y.div_(x)
print(y)

tensor([[1.2751, 1.0457],
        [1.3105, 2.0586]])
tensor([[1.2751, 1.0457],
        [1.3105, 2.0586]])
tensor([[0.7843, 0.9563],
        [0.7631, 0.4858]])


### Slicing

In [23]:
x = torch.rand(5,3)
print(x)

tensor([[0.8949, 0.8538, 0.2626],
        [0.6967, 0.5297, 0.8642],
        [0.4015, 0.7891, 0.7276],
        [0.5551, 0.5602, 0.8276],
        [0.7842, 0.5106, 0.4896]])


In [25]:
# select the first column of x
sliced = x[:,0]
print(sliced)

tensor([0.8949, 0.6967, 0.4015, 0.5551, 0.7842])


In [26]:
# select the first row of x
sliced = x[0,:]
print(sliced)

tensor([0.8949, 0.8538, 0.2626])


Select one element

In [27]:
print(x[1,2])

tensor(0.8642)


.item() is used to get the value of a tensor with only one element

In [28]:
x[3,2].item()

0.827627956867218

### Reshaping x.view(dim1, dim2, ...)

In [38]:
x = torch.rand(4,4)
print(x)

tensor([[0.5339, 0.2532, 0.3904, 0.4056],
        [0.2179, 0.5938, 0.6831, 0.7916],
        [0.7633, 0.4285, 0.1432, 0.2519],
        [0.0933, 0.5149, 0.4028, 0.4781]])


In [39]:
y = x.view(16)
print(y)

tensor([0.5339, 0.2532, 0.3904, 0.4056, 0.2179, 0.5938, 0.6831, 0.7916, 0.7633,
        0.4285, 0.1432, 0.2519, 0.0933, 0.5149, 0.4028, 0.4781])


In [41]:
y = x.view(-1,8)
print(y)

print()
print(y.size())

tensor([[0.5339, 0.2532, 0.3904, 0.4056, 0.2179, 0.5938, 0.6831, 0.7916],
        [0.7633, 0.4285, 0.1432, 0.2519, 0.0933, 0.5149, 0.4028, 0.4781]])

torch.Size([2, 8])


Using -1 to infer the correct size

In [44]:
y = x.view(-1,2)
print(y)

print()
print(y.size())

tensor([[0.5339, 0.2532],
        [0.3904, 0.4056],
        [0.2179, 0.5938],
        [0.6831, 0.7916],
        [0.7633, 0.4285],
        [0.1432, 0.2519],
        [0.0933, 0.5149],
        [0.4028, 0.4781]])

torch.Size([8, 2])


In [45]:
y = x.view(-1,4)
print(y)

print()
print(y.size())

tensor([[0.5339, 0.2532, 0.3904, 0.4056],
        [0.2179, 0.5938, 0.6831, 0.7916],
        [0.7633, 0.4285, 0.1432, 0.2519],
        [0.0933, 0.5149, 0.4028, 0.4781]])

torch.Size([4, 4])


In [46]:
y = x.view(-1,2,2)
print(y)

print()
print(y.size())

tensor([[[0.5339, 0.2532],
         [0.3904, 0.4056]],

        [[0.2179, 0.5938],
         [0.6831, 0.7916]],

        [[0.7633, 0.4285],
         [0.1432, 0.2519]],

        [[0.0933, 0.5149],
         [0.4028, 0.4781]]])

torch.Size([4, 2, 2])


### From tensor to numpy array

In [47]:
import numpy as np 

In [64]:
a = torch.ones(5)
print(a, type(a))

tensor([1., 1., 1., 1., 1.]) <class 'torch.Tensor'>


In [65]:
b = a.numpy()
print(b, type(b))

[1. 1. 1. 1. 1.] <class 'numpy.ndarray'>


Be careful! If the tensor is on the CPU (not the GPU) both objects will share the same memory location. So if you change one, the other will change as well.

In [66]:
a.add_(1)
print(a)

tensor([2., 2., 2., 2., 2.])


In [67]:
print(b)

[2. 2. 2. 2. 2.]


### From numpy to tensor

In [69]:
a = np.ones(7)
print(a, type(a))

[1. 1. 1. 1. 1. 1. 1.] <class 'numpy.ndarray'>


In [70]:
b = torch.from_numpy(a)
print(b, type(b))

tensor([1., 1., 1., 1., 1., 1., 1.], dtype=torch.float64) <class 'torch.Tensor'>


In [71]:
a += 1
print(a)

[2. 2. 2. 2. 2. 2. 2.]


In [72]:
print(b)

tensor([2., 2., 2., 2., 2., 2., 2.], dtype=torch.float64)


The tensor has changed also!

### CUDA

Create tensor on the GPU 

In [73]:
if torch.cuda.is_available():
    
    device = torch.device("cuda")

    # write tensor to GPU
    x = torch.ones(5, device=device)

    # write tensor to CPU
    y = torch.ones(5)

    # move tensor to GPU
    y = y.to(device)

    # perform operation on GPU
    z = x + y  

    # cannot move directly to CPU
    #z.numpy()

    z = z.to("cpu")
    z.numpy()

