The training loop in PyTorch is split into multiple batches to make the training process more computationally efficient. By processing the data in smaller batches, the memory usage is reduced, and the model can be trained on more data without running out of memory. Additionally, updating the model parameters after processing each batch allows for more frequent adjustments to the model, which can improve its convergence towards a better solution. Moreover, training on smaller batches helps reduce the noise in the gradients computation, which can be beneficial in avoiding overfitting and preventing convergence to suboptimal solutions.

What I have used until now: 

In [ ]:
X,y = load_data

for epoch in epochs:
    # forwards pass
    # loss
    # backwards pass
    # update weights


Instead, it is common to build a second for loop to iterate through batches of the training data: 

In [ ]:
for epoch in epochs:

    for batch in n_batches:

        x_batch, y_batch = ... 


The notation ends up like: 

**epoch**: one complete forward and backward pass through all training samples. 

**batch_size** = number of training samples in one forward and backward pass and weight update. 

**iteration**: one forward and backward pass and weight update. 

Each epoch has a certain **number of iterations** needed to go through all batches. 

Example: 100 samples, batch_size = 20 --> 5 iterations for each epoch. 

In [1]:
import torch 
import torchvision 
from torch.utils.data import Dataset, DataLoader

import math 
import numpy as np 

### Dataset

In [2]:
# MiPropioDataset inherits from the class Dataset
class MiPropioDataset(Dataset):

    def __init__(self):
        # data loading 
        data = np.loadtxt('../datasets/wine.csv', delimiter= ',', skiprows= 1)
        self.x = torch.from_numpy(data[:,1:].astype(np.float32))
        self.y = torch.from_numpy(data[:,[0]].astype(np.float32))

        self.n_samples, self.n_features = self.x.shape


    def __getitem__(self, index):
        return self.x[index], self.y[index]

    def __len__(self):
        # len(dataset)
        return self.n_samples

    def __n_features__(self):
        return self.n_features

In [3]:
prueba_dataset = MiPropioDataset()

features_0, label_0  = prueba_dataset[0]

print(features_0, label_0 )


tensor([1.4230e+01, 1.7100e+00, 2.4300e+00, 1.5600e+01, 1.2700e+02, 2.8000e+00,
        3.0600e+00, 2.8000e-01, 2.2900e+00, 5.6400e+00, 1.0400e+00, 3.9200e+00,
        1.0650e+03]) tensor([1.])


### DataLoader

In [4]:
dataloader = DataLoader(dataset= prueba_dataset,
                        batch_size= 4,
                        shuffle= True,
                        #num_workers= 1,
                        )

dataiter = iter(dataloader)

data = next(dataiter)

features, labels  = data

print(features, labels)


tensor([[1.2670e+01, 9.8000e-01, 2.2400e+00, 1.8000e+01, 9.9000e+01, 2.2000e+00,
         1.9400e+00, 3.0000e-01, 1.4600e+00, 2.6200e+00, 1.2300e+00, 3.1600e+00,
         4.5000e+02],
        [1.3940e+01, 1.7300e+00, 2.2700e+00, 1.7400e+01, 1.0800e+02, 2.8800e+00,
         3.5400e+00, 3.2000e-01, 2.0800e+00, 8.9000e+00, 1.1200e+00, 3.1000e+00,
         1.2600e+03],
        [1.2640e+01, 1.3600e+00, 2.0200e+00, 1.6800e+01, 1.0000e+02, 2.0200e+00,
         1.4100e+00, 5.3000e-01, 6.2000e-01, 5.7500e+00, 9.8000e-01, 1.5900e+00,
         4.5000e+02],
        [1.1650e+01, 1.6700e+00, 2.6200e+00, 2.6000e+01, 8.8000e+01, 1.9200e+00,
         1.6100e+00, 4.0000e-01, 1.3400e+00, 2.6000e+00, 1.3600e+00, 3.2100e+00,
         5.6200e+02]]) tensor([[2.],
        [1.],
        [2.],
        [2.]])


In [5]:
data = next(dataiter)

features, labels  = data

print(features, labels)

tensor([[1.2370e+01, 1.1300e+00, 2.1600e+00, 1.9000e+01, 8.7000e+01, 3.5000e+00,
         3.1000e+00, 1.9000e-01, 1.8700e+00, 4.4500e+00, 1.2200e+00, 2.8700e+00,
         4.2000e+02],
        [1.3560e+01, 1.7100e+00, 2.3100e+00, 1.6200e+01, 1.1700e+02, 3.1500e+00,
         3.2900e+00, 3.4000e-01, 2.3400e+00, 6.1300e+00, 9.5000e-01, 3.3800e+00,
         7.9500e+02],
        [1.2960e+01, 3.4500e+00, 2.3500e+00, 1.8500e+01, 1.0600e+02, 1.3900e+00,
         7.0000e-01, 4.0000e-01, 9.4000e-01, 5.2800e+00, 6.8000e-01, 1.7500e+00,
         6.7500e+02],
        [1.2220e+01, 1.2900e+00, 1.9400e+00, 1.9000e+01, 9.2000e+01, 2.3600e+00,
         2.0400e+00, 3.9000e-01, 2.0800e+00, 2.7000e+00, 8.6000e-01, 3.0200e+00,
         3.1200e+02]]) tensor([[2.],
        [1.],
        [3.],
        [2.]])


### Dummy training loop over our dataset

In [7]:
num_epochs = 5 # for example 

batch_size = 4 # for example

# total samples and iterations necessary 
total_samples = len(prueba_dataset)

# redondea hacia arriba 
num_iter = math.ceil(total_samples/batch_size)

print(total_samples, num_iter)

178 45


### Iterate over dataloader = DataLoader(dataset= prueba_dataset, batch_size... ) 


In [14]:
for idx, (input,label) in enumerate(dataloader):
    print(idx, '\n Input:', input, '\n Label:', label)
    print('')

0 
 Input: tensor([[1.3200e+01, 1.7800e+00, 2.1400e+00, 1.1200e+01, 1.0000e+02, 2.6500e+00,
         2.7600e+00, 2.6000e-01, 1.2800e+00, 4.3800e+00, 1.0500e+00, 3.4000e+00,
         1.0500e+03],
        [1.3070e+01, 1.5000e+00, 2.1000e+00, 1.5500e+01, 9.8000e+01, 2.4000e+00,
         2.6400e+00, 2.8000e-01, 1.3700e+00, 3.7000e+00, 1.1800e+00, 2.6900e+00,
         1.0200e+03],
        [1.3280e+01, 1.6400e+00, 2.8400e+00, 1.5500e+01, 1.1000e+02, 2.6000e+00,
         2.6800e+00, 3.4000e-01, 1.3600e+00, 4.6000e+00, 1.0900e+00, 2.7800e+00,
         8.8000e+02],
        [1.2080e+01, 2.0800e+00, 1.7000e+00, 1.7500e+01, 9.7000e+01, 2.2300e+00,
         2.1700e+00, 2.6000e-01, 1.4000e+00, 3.3000e+00, 1.2700e+00, 2.9600e+00,
         7.1000e+02]]) 
 Label: tensor([[1.],
        [1.],
        [1.],
        [2.]])

1 
 Input: tensor([[1.3320e+01, 3.2400e+00, 2.3800e+00, 2.1500e+01, 9.2000e+01, 1.9300e+00,
         7.6000e-01, 4.5000e-01, 1.2500e+00, 8.4200e+00, 5.5000e-01, 1.6200e+00,
         6.5

In [16]:
for epoch in range(num_epochs):
    for idx, (input, label) in enumerate(dataloader):

        if (idx+1)%5 == 0:
            print(f'Epoch{epoch+1}\{num_epochs} ; step {idx+1}\{num_iter}')
    

Epoch1\5 ; step 5\45
Epoch1\5 ; step 10\45
Epoch1\5 ; step 15\45
Epoch1\5 ; step 20\45
Epoch1\5 ; step 25\45
Epoch1\5 ; step 30\45
Epoch1\5 ; step 35\45
Epoch1\5 ; step 40\45
Epoch1\5 ; step 45\45
Epoch2\5 ; step 5\45
Epoch2\5 ; step 10\45
Epoch2\5 ; step 15\45
Epoch2\5 ; step 20\45
Epoch2\5 ; step 25\45
Epoch2\5 ; step 30\45
Epoch2\5 ; step 35\45
Epoch2\5 ; step 40\45
Epoch2\5 ; step 45\45
Epoch3\5 ; step 5\45
Epoch3\5 ; step 10\45
Epoch3\5 ; step 15\45
Epoch3\5 ; step 20\45
Epoch3\5 ; step 25\45
Epoch3\5 ; step 30\45
Epoch3\5 ; step 35\45
Epoch3\5 ; step 40\45
Epoch3\5 ; step 45\45
Epoch4\5 ; step 5\45
Epoch4\5 ; step 10\45
Epoch4\5 ; step 15\45
Epoch4\5 ; step 20\45
Epoch4\5 ; step 25\45
Epoch4\5 ; step 30\45
Epoch4\5 ; step 35\45
Epoch4\5 ; step 40\45
Epoch4\5 ; step 45\45
Epoch5\5 ; step 5\45
Epoch5\5 ; step 10\45
Epoch5\5 ; step 15\45
Epoch5\5 ; step 20\45
Epoch5\5 ; step 25\45
Epoch5\5 ; step 30\45
Epoch5\5 ; step 35\45
Epoch5\5 ; step 40\45
Epoch5\5 ; step 45\45
